INSERT INTO HR.POST
(POST_ID, POST_TITLE, POST_CONTENT, POST_IMG_PATH, ATTRLOC1, ATTRLOC2, POST_THEME_ID, POST_DELFLAG, POST_REGDATE, POST_LIKE_COUNT, POST_VIEW_COUNT, ID, BOOKNO)
VALUES(5, 'POST_TEST', 'POST_TEST_CONTENT', 'https://openimage.interpark.com/dia/images/179/2/201109002/601ad3bbc7fb497a88c32726d16e4ebe.jpg', 1, 1, 2, 'N', SYSDATE, 0, 0, '3', 1);

UPDATE HR.POST
SET POST_IMG_PATH= 'https://openimage.interpark.com/dia/images/179/2/201109002/601ad3bbc7fb497a88c32726d16e4ebe.jpg'
WHERE POST_ID=1;



INSERT INTO HR."MEMBER"
(ID, PASSWORD, NAME, NICKNAME, PHONE, EMAIL, JOINDATE, DELFLAG, MANAGER, FINAL_LOGIN, PANALTY, PANALTY_TERM, SNSJOIN)
VALUES('3', '', '', '', '', '', '', 'N', '', '', '', '', '');


INSERT INTO HR.MYTOURBOOK
(BOOKNO, TITLE, AURTHOR, REGDATE, KEYWORD, DELFLAG)
VALUES(1, 'TEST', '1', SYSDATE, 'TEST', 'N');

INSERT INTO HR.THEME
(THEME_ID, THEME_NAME)
VALUES(1, 'TEST');


SELECT POST_ID, POST_TITLE, POST_CONTENT, POST_IMG_PATH, ATTRLOC1, ATTRLOC2, POST_THEME_ID, POST_DELFLAG, POST_REGDATE, POST_LIKE_COUNT, POST_VIEW_COUNT, ID, BOOKNO
FROM HR.POST;

INSERT INTO HR.USER_FOLLOW
(USER_FOLLOW_ID, FOLLOW_ID, FOLLOWING_ID)
VALUES(2, '1', '3');

SELECT POST_ID,
		POST_TITLE, POST_CONTENT, POST_IMG_PATH, 
		ATTRLOC1, ATTRLOC2, POST_THEME_ID, 
		POST_DELFLAG, POST_REGDATE, POST_LIKE_COUNT,
		POST_VIEW_COUNT, ID, BOOKNO
		FROM HR.POST p
		WHERE p.ID IN (SELECT FOLLOWING_ID FROM USER_FOLLOW WHERE FOLLOW_ID = '1')

INSERT INTO HR.THEME
(THEME_ID, THEME_NAME)
VALUES(2, 'TEST2');

		
SELECT THEME_ID, THEME_NAME
FROM HR.THEME;



INSERT INTO HR.THEME_FOLLOW
(THEME_FOLLOW_ID, THEME_FOLLOWING_ID, USERID)
VALUES(2, 2, '1');

SELECT * FROM THEME_FOLLOW

		
SELECT POST_ID, POST_TITLE, POST_CONTENT, POST_IMG_PATH, ATTRLOC1, ATTRLOC2, POST_THEME_ID, POST_DELFLAG, POST_REGDATE, POST_LIKE_COUNT, POST_VIEW_COUNT, ID, BOOKNO
FROM HR.POST p
	WHERE p.POST_THEME_ID IN (SELECT THEME_FOLLOWING_ID FROM THEME_FOLLOW tf WHERE USERID = '1')
;
 



