INSERT INTO HR.POST
(POST_ID, POST_TITLE, POST_CONTENT, POST_IMG_PATH, ATTRLOC1, ATTRLOC2, POST_THEME_ID, POST_DELFLAG, POST_REGDATE, POST_LIKE_COUNT, POST_VIEW_COUNT, ID, BOOKNO)
VALUES(2, 'POST_TEST', 'POST_TEST_CONTENT', 'https://openimage.interpark.com/dia/images/179/2/201109002/601ad3bbc7fb497a88c32726d16e4ebe.jpg', 1, 1, 1, 'N', SYSDATE, 0, 0, '2', 1);

UPDATE HR.POST
SET POST_IMG_PATH= 'https://openimage.interpark.com/dia/images/179/2/201109002/601ad3bbc7fb497a88c32726d16e4ebe.jpg'
WHERE POST_ID=1;



INSERT INTO HR."MEMBER"
(ID, PASSWORD, NAME, NICKNAME, PHONE, EMAIL, JOINDATE, DELFLAG, MANAGER, FINAL_LOGIN, PANALTY, PANALTY_TERM, SNSJOIN)
VALUES('2', '', '', '', '', '', '', 'N', '', '', '', '', '');


INSERT INTO HR.MYTOURBOOK
(BOOKNO, TITLE, AURTHOR, REGDATE, KEYWORD, DELFLAG)
VALUES(1, 'TEST', '1', SYSDATE, 'TEST', 'N');

INSERT INTO HR.THEME
(THEME_ID, THEME_NAME)
VALUES(1, 'TEST');


SELECT POST_ID, POST_TITLE, POST_CONTENT, POST_IMG_PATH, ATTRLOC1, ATTRLOC2, POST_THEME_ID, POST_DELFLAG, POST_REGDATE, POST_LIKE_COUNT, POST_VIEW_COUNT, ID, BOOKNO
FROM HR.POST;

INSERT INTO HR.USER_FOLLOW
(USER_FOLLOW_ID, FOLLOW_ID, FOLLOWING_ID)
VALUES(1, '1', '2');

SELECT POST_ID, POST_TITLE, POST_CONTENT, POST_IMG_PATH, ATTRLOC1, ATTRLOC2, POST_THEME_ID, POST_DELFLAG, POST_REGDATE, POST_LIKE_COUNT, POST_VIEW_COUNT, ID, BOOKNO
FROM HR.POST p, USER_FOLLOW uf 
WHERE p.ID = (SELECT FOLLOWING_ID FROM USER_FOLLOW uf2 WHERE uf2.FOLLOW_ID = '1')



