--글 작성
INSERT INTO REPORT (REPORT_NUM, TITLE, CONTENT, 
					REFER, STEP, "DEPTH", 
					DELFLAG, REGDATE, SECRETFLAG, 
					USERID )
	VALUES(REPORT_SEQ.NEXTVAL,'TITLE','CONTENT',
			(SELECT NVL(MAX(REPORT_NUM),0) FROM REPORT)+1,0,0,
			'N',SYSDATE,'N',
			'qwer123');

--전체 글 조회
SELECT REPORT_NUM, TITLE, CONTENT, 
		REFER, STEP, "DEPTH", 
		DELFLAG, REGDATE, SECRETFLAG,
		USERID 
	FROM REPORT r 
	WHERE DELFLAG = 'N'
	ORDER BY REFER DESC, STEP 
	
--글 상세 조회
SELECT * FROM REPORT r 
		WHERE REPORT_NUM =1;

--글 삭제
UPDATE REPORT SET DELFLAG = 'Y'
	WHERE REPORT_NUM =1;

--글 수정
UPDATE REPORT SET TITLE='ASDF', CONTENT='ASDF', SECRETFLAG='N'
			WHERE REPORT_NUM = 1;

--답글작성 1단계 - UPDATE
UPDATE REPORT SET STEP = STEP+1
		WHERE REFER=(SELECT REFER FROM REPORT WHERE REPORT_NUM = '1')
		AND STEP >(SELECT STEP FROM REPORT WHERE REPORT_NUM =1)
			

--답글작성 2단계 - INSERT
INSERT INTO REPORT (REPORT_NUM, TITLE, CONTENT, 
					REFER, STEP, "DEPTH", 
					DELFLAG, REGDATE, SECRETFLAG, 
					USERID )
			VALUES(REPORT_SEQ.NEXTVAL, 'TITLE','CONTENT',
					(SELECT REFER FROM REPORT r WHERE REPORT_NUM=1), (SELECT STEP FROM REPORT r WHERE REPORT_NUM=1)+1, (SELECT "DEPTH" FROM REPORT r WHERE REPORT_NUM=1)+1,
					'N', SYSDATE, 'N',
					'qwer123');
					


	
	
	
	
	
	