UPDATE MYTOURBOOK
	SET TITLE='', AURTHOR='', REGDATE='', KEYWORD='', DELFLAG=''
WHERE BOOKNO=0;

SELECT BOOKNO, TITLE, AURTHOR, REGDATE, KEYWORD, DELFLAG
FROM MYTOURBOOK;

DELETE FROM MYTOURBOOK
WHERE BOOKNO=0;

INSERT INTO MYTOURBOOK
(BOOKNO, TITLE, AURTHOR, REGDATE, KEYWORD, DELFLAG)
VALUES(BOOKNO_SEQ.NEXTVAL, '', '', '', '', '');

CREATE SEQUENCE BOOKNO_SEQ START WITH 1 INCREMENT BY 1;