UPDATE MYTOURBOOK
	SET TITLE='', AURTHOR='', REGDATE='', KEYWORD='', DELFLAG=''
WHERE BOOKNO=0;

SELECT BOOKNO, TITLE, AURTHOR, REGDATE, KEYWORD, DELFLAG
FROM MYTOURBOOK;

DELETE FROM MYTOURBOOK
WHERE BOOKNO=0;

INSERT INTO MYTOURBOOK
(BOOKNO, TITLE, AURTHOR, REGDATE, KEYWORD, DELFLAG)
VALUES(BOOKNO_SEQ.NEXTVAL, '', '', '', '', '');

CREATE SEQUENCE BOOKNO_SEQ START WITH 1 INCREMENT BY 1;


SELECT BOOKNO,TITLE,AURTHOR,TO_CHAR(REGDATE,'YYYY-MM-DD') REGDATE,KEYWORD,DELFLAG
 			FROM MYTOURBOOK
 				WHERE BOOKNO= 1;
 				
 			
SELECT DATANO, BOOKNO, ATTRLOC1, ATTRLOC2, TOURORDER, CONTENTID
FROM MYTOURDATA;

INSERT INTO MYTOURDATA
(DATANO, BOOKNO, ATTRLOC1, ATTRLOC2, TOURORDER, CONTENTID)
VALUES(DATANO_SEQ.NEXTVAL, 0, 0, 0, 0, 0);

CREATE SEQUENCE DATANO_SEQ START WITH 1 INCREMENT BY 1;


DELETE FROM MYTOURDATA
WHERE DATANO=0;


UPDATE MYTOURDATA
SET BOOKNO=0, ATTRLOC1=0, ATTRLOC2=0, TOURORDER=0, CONTENTID=0
WHERE DATANO=0;

SELECT BOOKNO,TITLE,AURTHOR,TO_CHAR(REGDATE,'YYYY-MM-DD') REGDATE,KEYWORD,DELFLAG
 			FROM MYTOURBOOK
 				WHERE TITLE LIKE '%insert%';
SELECT DATANO, BOOKNO, ATTRLOC1, ATTRLOC2, TOURORDER, CONTENTID
			FROM MYTOURDATA WHERE BOOKNO=1;
