-- 상품 등록
INSERT INTO PRODUCTS (PRODUCT_CODE, NAME, PRICE, DESCRIPTION, REG_DATE, DELFLAG, UPDATE_DATE) 
	VALUES (1, '문서화', 1000, '문서출력 이용 금액', SYSDATE, 'N', SYSDATE);
INSERT INTO PRODUCTS (PRODUCT_CODE, NAME, PRICE, DESCRIPTION, REG_DATE, DELFLAG, UPDATE_DATE) 
	VALUES (PRODUCTS_SEQ.NEXTVAL, '인벤토리추가', 1000, '마이투어 인벤토리 추가 이용 금액', SYSDATE, 'N', SYSDATE);
	
-- 상품 전체조회
SELECT PRODUCT_CODE, NAME, PRICE, DESCRIPTION, TO_CHAR(REG_DATE, 'YYYY-MM-DD') AS REG_DATE, DELFLAG, TO_CHAR(UPDATE_DATE, 'YYYY-MM-DD') AS UPDATE_DATE
	FROM PRODUCTS
	WHERE DELFLAG = 'N';
-- 상품 단일조회(seq)
SELECT PRODUCT_CODE, NAME, PRICE, DESCRIPTION, TO_CHAR(REG_DATE, 'YYYY-MM-DD') AS REG_DATE, UPDATE_DATE
	FROM PRODUCTS 
	WHERE PRODUCT_CODE = 1;
-- 상품 이름으로 조회
SELECT PRODUCT_CODE, NAME, PRICE, DESCRIPTION, TO_CHAR(REG_DATE, 'YYYY-MM-DD') AS REG_DATE, DELFLAG, TO_CHAR(UPDATE_DATE, 'YYYY-MM-DD') AS UPDATE_DATE
	FROM PRODUCTS 
	WHERE NAME LIKE '%문%';
-- 상품 삭제(delflag)
UPDATE PRODUCTS 
	SET DELFLAG = 'N'
	WHERE PRODUCT_CODE = 1;
-- 상품 수정
UPDATE PRODUCTS 
	SET NAME = '문서화2', PRICE = 1500, DESCRIPTION ='문서출력 이용 금액2', UPDATE_DATE = SYSDATE
	WHERE PRODUCT_CODE = 1;


-- 결제 내역 등록(관리자)
INSERT INTO PAYMENTS (PAYCODE, IMP_UID, PG, PAY_METHOD, CARD_NAME, PAY_STATE, PRICE, PAY_DATE, CANCELYN, CANCEL_DATE, CANCEL_DESC, PRODUCT_CODE, USERID, DELFLAG, UPDATE_DATE) 
	VALUES (PAYMENTS_SEQ.NEXTVAL, 'imp_684875265631', 'html5_inicis', 'card', '신한카드', 'paid', 10, SYSDATE, 'Y', NULL, NULL, 1, '아이디1', 'N', SYSDATE);
	
-- 결제 내역 전체 조회(관리자)
SELECT PAYCODE, IMP_UID, PG, PAY_METHOD, PAY_STATE, PRICE, PAY_DATE, CANCELYN, CANCEL_DATE, CANCEL_DESC, PRODUCT_CODE, USERID, DELFLAG, UPDATE_DATE
	FROM PAYMENTS;

-- 결제 내역 이름 조회(관리자)/전체내역 조회(사용자)
SELECT PAYCODE, IMP_UID, PG, PAY_METHOD, PAY_STATE, PRICE, PAY_DATE, CANCELYN, CANCEL_DATE, CANCEL_DESC, PRODUCT_CODE, USERID, DELFLAG, UPDATE_DATE
	FROM PAYMENTS
	WHERE USERID = '아이디1';

-- 결제 내역 상세 조회 (관리자, 사용자)
SELECT PAYCODE, IMP_UID, PG, PAY_METHOD, PAY_STATE, PRICE, PAY_DATE, CANCELYN, CANCEL_DATE, CANCEL_DESC, PRODUCT_CODE, USERID, DELFLAG, UPDATE_DATE
	FROM PAYMENTS
	WHERE PAYCODE = 1;
-- 결제 내역 삭제(delflag)(관리자)
UPDATE PAYMENTS 
	SET DELFLAG = 'Y', UPDATE_DATE = SYSDATE 
	WHERE PAYCODE = 1 AND USERID = '아이디1';

-- 결제 내역 수정(결제 취소 불가로 변경)(관리자)
UPDATE PAYMENTS 
	SET CANCELYN = 'Y', UPDATE_DATE = SYSDATE 
	WHERE PAYCODE = 1 AND IMP_UID = 'imp_684875265630';
	
-- 결제 취소
UPDATE PAYMENTS 
	SET PAY_STATE = 'CANCEL', CANCEL_DATE = SYSDATE, CANCEL_DESC = '테스트', UPDATE_DATE = SYSDATE 
	WHERE PAYCODE = 7 AND IMP_UID = 'imp_058793286063';
	
-- 유저 생성
INSERT INTO "MEMBER"
(ID, PASSWORD, NAME, NICKNAME, PHONE, EMAIL, JOINDATE, PROFILE_IMG_PATH, DELFLAG, MANAGER, FINAL_LOGIN, PANALTY, PANALTY_END_DATE, DORMANCYFLAG, SNSJOIN)
VALUES('MANAGER1', 1234, '매니저1', '매니저1', '010', 'email', sysdate, null, 'N', 'Y', null, null, null, null, 'N');




---코드 테스트
SELECT PAYCODE, IMP_UID, PG, 
			   PAY_METHOD, PAY_STATE, PRICE, 
			   PAY_DATE, CANCELYN, CANCEL_DATE, 
			   CANCEL_DESC, PRODUCT_CODE, USERID, 
			   DELFLAG
			FROM PAYMENTS
			WHERE USERID = '1';
			
DELETE FROM PAYMENTS;		